name: "Client"
on:
  push:
    branches: [ "client" ]
  pull_request:
    branches: [ "client" ]

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Deploy client
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_CLIENT_APP_NAME }}
          dockerfile_directory: ./client

          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web